# -*- coding: utf-8 -*-
"""Numpy_Assesment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3FnqqOwz__fNR3Ol-kgxM7RUTOCuEp1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1) Import pandas and read in the banklist.csv file into a dataframe calledbanks.
banks = pd.read_csv("/content/Data_for_Numpy_Assesment.csv")

# 2) Show the head of the dataframe.
display(banks.head())

# 3) What are the column names?
display(banks.columns)

# 4) How many States (ST) are represented in this data set?
display(banks['ST'].nunique())

# 5) Get a list or array of all the states in the data set.
display(banks['ST'].unique())

# 6) What are the top 5 states with the most failed banks?
display(banks['ST'].value_counts().head(5))

# 7) What are the top 5 acquiring institutions?
display(banks['Acquiring Institution'].value_counts().head(5))

# 8) How many banks has the State Bank of Texas acquired? How many of them were actually in Texas?

sbt_acquisitions = banks[banks['Acquiring Institution'] == 'State Bank of Texas']

total_acquired = len(sbt_acquisitions)
print(f"Total banks acquired by State Bank of Texas is: {total_acquired}")

in_texas_acquired = len(sbt_acquisitions[sbt_acquisitions['ST'] == 'TX'])
print(f"Banks acquired by State Bank of Texas that were in Texas is: {in_texas_acquired}")

# 9) What is the most common city in California for a bank to fail in?

california_banks = banks[banks['ST'] == 'CA']

# Count the occurrences of each city in California and get the most common one
most_common_city_ca = california_banks['City'].value_counts().idxmax()
print(f"The most common city in California for a bank to fail-in is: {most_common_city_ca}")

automobile = pd.read_csv("/content/Auto_Data_for_Numpy_Assesment.csv")

# automobile.head()
automobile.columns

# Q 1: Develop a Line chart using the functionality of pandas to show how automobile sales fluctuate from year to year.

yearly_sales = automobile.groupby('Year')['Automobile_Sales'].sum()

yearly_sales.plot(kind='line', figsize=(10, 6), title='Automobile Sales Fluctuation Year-to-Year')
plt.xlabel('Year')
plt.ylabel('Total Automobile Sales')
plt.grid(True)
plt.show()

# Q 2: Plot different lines for categories of vehicle type and analyze the trend to answer the question Is there a noticeable difference in sales trendsbetween different vehicle types during recession periods?

# Filter data for recession periods
recession_data = automobile[automobile['Recession'] == 1]

# Aggregate sales by Year, Month, and Vehicle_Type for recession periods
recession_sales_by_vehicle = recession_data.groupby(['Year', 'Month', 'Vehicle_Type'])['Automobile_Sales'].sum().reset_index()

# Create a date column for plotting
recession_sales_by_vehicle['Date'] = pd.to_datetime(recession_sales_by_vehicle['Year'].astype(str) + '-' + recession_sales_by_vehicle['Month'], format='%Y-%b')

plt.figure(figsize=(14, 7))
sns.lineplot(data=recession_sales_by_vehicle, x='Date', y='Automobile_Sales', hue='Vehicle_Type', marker='o')
plt.title('Automobile Sales Trends by Vehicle Type During Recession Periods')
plt.xlabel('Date')
plt.ylabel('Total Automobile Sales')
plt.grid(True)
plt.tight_layout()
plt.show()

# Q 3: Use the functionality of Seaborn Library to create a visualization to compare the sales trend per vehicle type for a recession period with a non-recession period.

# Filter data for recession and non-recession periods
recession_data = automobile[automobile['Recession'] == 1]
non_recession_data = automobile[automobile['Recession'] == 0]

# Aggregate sales by Year, Month, and Vehicle_Type for recession periods
recession_sales_by_vehicle = recession_data.groupby(['Year', 'Month', 'Vehicle_Type'])['Automobile_Sales'].sum().reset_index()
recession_sales_by_vehicle['Period'] = 'Recession'

# Aggregate sales by Year, Month, and Vehicle_Type for non-recession periods
non_recession_sales_by_vehicle = non_recession_data.groupby(['Year', 'Month', 'Vehicle_Type'])['Automobile_Sales'].sum().reset_index()
non_recession_sales_by_vehicle['Period'] = 'Non-Recession'

# Combine the two dataframes
combined_sales_data = pd.concat([recession_sales_by_vehicle, non_recession_sales_by_vehicle])

# Create a date column for plotting
combined_sales_data['Date'] = pd.to_datetime(combined_sales_data['Year'].astype(str) + '-' + combined_sales_data['Month'],format='%Y-%b')

plt.figure(figsize=(16, 8))
sns.lineplot(data=combined_sales_data, x='Date', y='Automobile_Sales', hue='Vehicle_Type', style='Period', marker='o')
plt.title('Automobile Sales Trends by Vehicle Type: Recession vs. Non-Recession Periods')
plt.xlabel('Date')
plt.ylabel('Total Automobile Sales')
plt.grid(True)
plt.legend(title='Period /')
plt.tight_layout()
plt.show()

# Q 4: Now you want to compare the sales of different vehicle types during a recession and a non-recession period.

# Aggregate sales by Vehicle_Type and Recession status
sales_comparison = automobile.groupby(['Recession', 'Vehicle_Type'])['Automobile_Sales'].sum().reset_index()

# Map Recession column to descriptive labels for better plotting
sales_comparison['Period'] = sales_comparison['Recession'].map({1: 'Recession', 0: 'Non-Recession'})

plt.figure(figsize=(12, 7))
sns.barplot(data=sales_comparison, x='Vehicle_Type', y='Automobile_Sales', hue='Period', palette='viridis')
plt.title('Automobile Sales Comparison by Vehicle Type: Recession vs. Non-Recession')
plt.xlabel('Vehicle Type')
plt.ylabel('Total Automobile Sales')
plt.legend(title='Period')
plt.tight_layout()
plt.show()