# -*- coding: utf-8 -*-
"""Pandas_Assesment.ipy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1asIj-pd5jJsz3CnBnNM_QJELGs0O8mGh
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

fed = pd.read_excel('/content/finance_economics_dataset_Numpy_Assesment.xlsx')

fed.head()

# QUE 1
print("The shape of the dataset is: ")
print(fed.shape)

# QUE 2
print("The column names and their data types are: ")
print(fed.dtypes)

# QUE 3
print("The Unique Stock Indices Are: ")
print(fed['Stock Index'].unique())

# QUE 4
print("The date range of the dataset is: ")
fed['Date'].agg(['min','max'])

# QUE 5
print("Any missing values: ")
fed.isnull().sum()

# QUE 6
print("Are there negative values in columns that should be non-negative: ")
fed.select_dtypes(include='number').lt(0).sum()

# QUE 7
print("The summary of GDP Growth(%) Is: ")
fed['GDP Growth (%)'].describe()

# QUE 8
print("Are there rows with zero or near-zero trading volume? ")
fed[fed['Trading Volume'] == 0]

# QUE 9
print("Are there any duplicate rows: ")
fed[fed.duplicated()]

# QUE 10
print("Are there outliers in GDP, Gold, or Oil prices: ")
import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(data=fed['Gold Price (USD per Ounce)'])
plt.show()
sns.boxplot(data=fed['Crude Oil Price (USD per Barrel)'])
plt.show()
sns.boxplot(data=fed['GDP Growth (%)'])
plt.show()

# QUE 11
print("The summary of Inflation Rate(%) is: ")
fed['GDP Growth (%)'].describe()

# QUE 12
print("The average unemployment rate is: ")
avg = fed['Unemployment Rate (%)'].mean().round(3)
print(avg)

# QUE 13
print("The Index Which has the highest trading volume is: ")
y = fed.groupby('Stock Index')['Trading Volume'].sum().idxmax()
print(y)
s = fed.groupby('Stock Index')['Trading Volume'].sum().max()
print(s)

# QUE 14
print("The stock records from each index are: ")
fed['Stock Index'].value_counts()

# QUE 15
print("The correlation between inflation and interest rate is: ")
fed[['Inflation Rate (%)', 'Interest Rate (%)']].corr()

# QUE 16
print("The average Consumer Confidence Index is: ")
cci = fed['Consumer Confidence Index'].mean()
print(cci)

# QUE 17
print('The Column which has highest standard deviation is: ')
std_values = fed.std(numeric_only=True)
std_values.idxmax(),std_values.max()

# QUE 18
print("The highest gold price recorded is: ")
fed.loc[fed['Gold Price (USD per Ounce)'].idxmax(),['Date', 'Gold Price (USD per Ounce)']]

# QUE 19
print("The Date when the highest crude oil price recorded is: ")
fed.loc[fed['Crude Oil Price (USD per Barrel)'].idxmax(),['Date','Crude Oil Price (USD per Barrel)']]

# QUE 20
print("The average corporate profit is: ")
acp = fed['Corporate Profits (Billion USD)'].mean().round(3)
print(acp)

fed.head()

# QUE 1
print("The percentage of the dataset shows negative GDP growth is: ")
ngg = ((fed['GDP Growth (%)'] < 0).mean() * 100).round(3)
print(ngg)

# QUE 2
print("Does high inflation correspond to higher interest rates")
x = fed['Inflation Rate (%)'].corr(fed['Interest Rate (%)'])
print(x)
print('\nHere Is the Chart Of it: ')
plt.scatter(fed['Inflation Rate (%)'],fed['Interest Rate (%)'])
plt.xlabel('Inflation Rate (%)')
plt.ylabel('Interest Rate (%)')
plt.show()

# QUE 3
print("Is there a relationship between unemployment and consumer spending: ")
v = fed[['Unemployment Rate (%)','Consumer Spending (Billion USD)']].corr()
print(v)
print("\nHere Is the Chart of it: ")
plt.scatter(fed['Unemployment Rate (%)'],fed['Consumer Spending (Billion USD)'])
plt.xlabel('Unemployment Rate (%)')
plt.ylabel('Consumer Spending (Billion USD)')
plt.show()

# QUE 4
print('Do higher corporate profits align with higher consumer confidence')
w = fed['Corporate Profits (Billion USD)'].corr(fed['Consumer Confidence Index'])
print(w)
print("\nHere Is the Chart of it: ")
plt.scatter(fed['Corporate Profits (Billion USD)'],fed['Consumer Confidence Index'])
plt.xlabel('Corporate Profits (Billion USD)')
plt.ylabel('Consumer Confidence Index')
plt.show()

# QUE 5
print("The trend of crude oil prices over time is: ")
plt.figure(figsize=(10,5))
plt.plot(fed['Date'], fed['Crude Oil Price (USD per Barrel)'])
plt.xlabel('Date')
plt.ylabel('Crude Oil Price (USD per Barrel)')
plt.title('Trend of Crude Oil Prices Over Time')
plt.show()

# QUE 6
print('Are gold prices inversely related to stock performance? ')
gold = fed['Gold Price (USD per Ounce)'].values
stocks = fed['Close Price'].values
correlation = np.corrcoef(gold, stocks)[0,1]
print(correlation)
print("\nHere Is the Chart of it: ")
plt.scatter(fed['Gold Price (USD per Ounce)'], fed['Close Price'])
plt.xlabel('Gold Price')
plt.ylabel('Stock Close Price')
plt.title('Gold vs Stock Performance')
plt.show()

# QUE 7
print('Does government debt impact consumer confidence? ')
debt = fed['Government Debt (Billion USD)'].values
confidence = fed['Consumer Confidence Index'].values
correlation = np.corrcoef(debt, confidence)[0,1]
print(correlation)
print("\nHere Is the Chart of it: ")
plt.scatter(debt, confidence)
plt.xlabel('Government Debt (Billion USD)')
plt.ylabel('Consumer Confidence Index')
plt.title('Government Debt vs Consumer Confidence')
plt.show()

# QUE 8
print('How do mergers & acquisitions (M&A) activity correlate with stock index closing prices')
for index in fed['Stock Index'].unique():
    subset = fed[fed['Stock Index'] == index]

    ma = subset['Mergers & Acquisitions Deals'].values
    close_price = subset['Close Price'].values

    corr = np.corrcoef(ma, close_price)[0,1]
    print(index, ":", corr)

print("\nHere Is the Chart of it: ")
plt.scatter(fed['Mergers & Acquisitions Deals'], fed['Close Price'])
plt.xlabel('M&A Deals')
plt.ylabel('Stock Close Price')
plt.title('M&A Activity vs Stock Prices')
plt.show()

# QUE 9
print("Is retail sales growth associated with GDP growth? ")
retail_growth = fed['Retail Sales (Billion USD)'].pct_change() * 100
gdp_growth = fed['GDP Growth (%)']
retail_growth = retail_growth[1:]
gdp_growth = gdp_growth[1:]
correlation = np.corrcoef(retail_growth, gdp_growth)[0,1]
print(correlation)

print("\nHere Is the Chart of it: ")
plt.scatter(retail_growth, gdp_growth)
plt.xlabel('Retail Sales Growth (%)')
plt.ylabel('GDP Growth (%)')
plt.title('Retail Sales Growth vs GDP Growth')
plt.show()

# QUE 10
print("Is stock market performance linked to consumer spending? ")
stock_return = fed['Close Price'].pct_change()
spending_growth = fed['Consumer Spending (Billion USD)'].pct_change()
stock_return = stock_return[1:]
spending_growth = spending_growth[1:]
correlation = np.corrcoef(stock_return, spending_growth)[0,1]
print(correlation)

print("\nHere Is the Chart of it: ")
plt.scatter(stock_return, spending_growth)
plt.xlabel('Stock Returns')
plt.ylabel('Consumer Spending Growth')
plt.title('Stock Performance vs Consumer Spending Growth')
plt.show()

# QUE 11
print("Which stock index had the highest average closing price? ")
avg_close = fed.groupby('Stock Index')['Close Price'].mean()
x = highest_index = avg_close.idxmax()
y = highest_value = avg_close.max()
print("Highest Index: ",x)
print("Highest Value: ",y)

# QUE 12
print("The relationship between interest rate and unemploymentis: ")
interest = fed['Interest Rate (%)'].values
unemployment = fed['Unemployment Rate (%)'].values
correlation = np.corrcoef(interest, unemployment)[0,1]
print(correlation)

print("\nHere Is the Chart of it: ")
plt.scatter(interest, unemployment)
plt.xlabel('Interest Rate (%)')
plt.ylabel('Unemployment Rate (%)')
plt.title('Interest Rate vs Unemployment')
plt.show()

# QUE 13
print("Do lower consumer confidence values coincide with higher bankruptcy rates? ")
confidence = fed['Consumer Confidence Index'].values
bankruptcy = fed['Bankruptcy Rate (%)'].values
correlation = np.corrcoef(confidence, bankruptcy)[0,1]
print(correlation)

print("\nHere Is the Chart of it: ")
plt.scatter(confidence, bankruptcy)
plt.xlabel('Consumer Confidence Index')
plt.ylabel('Bankruptcy Rate (%)')
plt.title('Consumer Confidence vs Bankruptcy Rate')
plt.show()

# QUE 14
print("Which indicator has the highest correlation with stock close price? ")
a = numeric_cols = fed.select_dtypes(include=np.number)
b = corr_matrix = numeric_cols.corr()
c = close_corr = corr_matrix['Close Price'].drop('Close Price')
highest_indicator = close_corr.abs().idxmax()
highest_value = close_corr[highest_indicator]
print(highest_indicator)
print(highest_value)

l = close_corr.abs().sort_values(ascending=False).head(5)
print("\n",l)

# QUE 15
print("Are unemployment rates lower when corporate profits are high? ")
profits = fed['Corporate Profits (Billion USD)'].values
unemployment = fed['Unemployment Rate (%)'].values
correlation = np.corrcoef(profits, unemployment)[0,1]
print(correlation)

print("\nHere Is the Chart of it: ")
plt.scatter(profits, unemployment)
plt.xlabel('Corporate Profits (Billion USD)')
plt.ylabel('Unemployment Rate (%)')
plt.title('Corporate Profits vs Unemployment')
plt.show()

retail = pd.read_excel("/content/sample_data/Retail Data_for_assesment.xlsx")

retail.head()
retail.columns

# QUE 1
print("1. Dataset Structure (columns, types, non-nulls):")
retail.info()
print("\nMissing values per column:")
print(retail.isnull().sum())

# QUE 2
print("2. The shape of the dataset is:")
print(retail.shape)

# QUE 3
print("3. Are there any duplicate records?")
print("Number of duplicate records is:")
print("ANS:",retail.duplicated().sum())

# QUE 4
print("4. Missing values in Order Quantity (numeric column):")
print(retail[['Order Quantity']].isnull().sum())

# QUE 5
# 1. Clean and Convert Date Columns
date_cols = ['Order Date', 'Ship Date']
for col in date_cols:
    retail[col] = pd.to_datetime(retail[col], errors='coerce')
    print(f"{col} NaNs: {retail[col].isna().sum()}")

# 2. Clean and Convert Price Columns
price_cols = ['Cost Price', 'Retail Price', 'Profit Margin', 'Sub Total',
              'Discount $', 'Order Total', 'Shipping Cost', 'Total']

for col in price_cols:
    # Remove currency symbols and commas, then convert to numbers
    retail[col] = retail[col].replace(r'[\$,]', '', regex=True)
    retail[col] = pd.to_numeric(retail[col], errors='coerce')
    print(f"{col} NaNs: {retail[col].isna().sum()}")

print("\nFinal Data Types:")
print(retail[date_cols + price_cols].dtypes)

# QUE 6
print("6. Checking for future or inconsistent shipping dates:")
inconsistent_shipments = retail[retail['Ship Date'] < retail['Order Date']]
if inconsistent_shipments.empty:
    print("No inconsistent shipping dates found (all Ship Dates are on or after Order Dates).")
else:
    print("Found inconsistent shipping dates:")
    print(inconsistent_shipments[['Order No', 'Order Date', 'Ship Date']])

# QUE 7
# 1. Clean characters ($, and ,) from all price columns at once
retail[price_cols] = retail[price_cols].replace(r'[\$,]', '', regex=True)

# 2. Convert all price columns to numeric (NaN for errors)
retail[price_cols] = retail[price_cols].apply(pd.to_numeric, errors='coerce')

# 3. Quickly check results
print("Number of corrupted (NaN) entries per column:")
print(retail[price_cols].isna().sum())

print("\nNew Data Types:")
print(retail[price_cols].dtypes)

# QUE 8
print("8. Unique values in Customer Type:")
print(retail['Customer Type'].unique())

print("\nUnique values in Order Priority:")
print(retail['Order Priority'].unique())

# QUE 9
print("9. Most common shipping modes:")
print(retail['Ship Mode'].value_counts())

# QUE 10
print("10. Which cities have the highest number of orders?")
print(retail['City'].value_counts().head(10))

# QUE 11
cols_to_check = ['Order Quantity'] + price_cols

print("11. Range of order quantities and prices:")
print(retail[cols_to_check].agg(['min', 'max']).T)

# QUE 12
# Calculate the days and save to the new column
retail['Shipping Duration'] = (retail['Ship Date'] - retail['Order Date']).dt.days

print("12. Shipping Duration (First 5 Rows):")
print(retail[['Order Date', 'Ship Date', 'Shipping Duration']].head())

# QUE 13
# 1. Filter for the "bad" data
invalid_qty = retail[retail['Order Quantity'] <= 0]
invalid_total = retail[retail['Total'] <= 0]

# 2. Print counts and the first few rows (if any exist)
print(f"13. Found {len(invalid_qty)} orders with zero/negative Quantity.")
if not invalid_qty.empty: print(invalid_qty[['Order No', 'Order Quantity']].head())

print(f"\nFound {len(invalid_total)} orders with zero/negative Total.")
if not invalid_total.empty: print(invalid_total[['Order No', 'Total']].head())

# QUE 14
# 1. Calculate the difference (Expected vs Actual)
retail['Discount Diff'] = (retail['Retail Price'] * retail['Order Quantity'] * (retail['Discount %'] / 100)) - retail['Discount $']

# 2. Filter for differences larger than 1 cent
mismatches = retail[retail['Discount Diff'].abs() > 0.01]

# 3. Print the results
print(f"14. Found {len(mismatches)} mismatched discount amounts.")
if not mismatches.empty:
    cols = ['Order No', 'Discount %', 'Discount $', 'Discount Diff']
    print(mismatches[cols].head())

# QUE 15
# 1. Calculate the difference between Expected and Actual
retail['Total Diff'] = (retail['Retail Price'] * retail['Order Quantity']) - retail['Discount $'] + retail['Shipping Cost'] - retail['Total']

# 2. Find mismatches larger than 1 cent
mismatches = retail[retail['Total Diff'].abs() > 0.01]

# 3. Print the result
print(f"15. Found {len(mismatches)} mismatched total calculations.")
if not mismatches.empty:
    cols = ['Order No', 'Total', 'Total Diff']
    print(mismatches[cols].head())

# QUE 16
print("16. Identify top 5 products by order quantity.")
print(retail.groupby('Product Name')['Order Quantity'].sum().nlargest(5))

# QUE 17
print("17. Which Account Manager handled the most revenue?")
most_revenue_manager = retail.groupby('Account Manager')['Total'].sum().idxmax()
highest_revenue_amount = retail.groupby('Account Manager')['Total'].sum().max()
print(f"The Account Manager who handled the most revenue is: {most_revenue_manager} with a total revenue of {highest_revenue_amount:.2f}")

# QUE 18
print("18. What is the average shipping cost by mode?")
print(retail.groupby('Ship Mode')['Shipping Cost'].mean())

# QUE 19
print("19. Find the most profitable product.")
most_profitable_product = retail.groupby('Product Name')['Profit Margin'].sum().idxmax()
highest_profit_margin = retail.groupby('Product Name')['Profit Margin'].sum().max()
print(f"The most profitable product is: {most_profitable_product} with a total profit margin of {highest_profit_margin:.2f}")

# Part 2 Of Assesment Starts From Here.

# 1. What is the total revenue generated across all orders?
retail['Total'] = retail['Total'].replace(r'[$,]', '', regex=True).astype(float)
revenue_generated = retail['Total'].sum()
print(f"The total revenue generated across all orders is: ${revenue_generated:,.2f}")

# 2. Which customer type generates more revenue?
revenue_by_customer_type = retail.groupby('Customer Type')['Total'].sum().sort_values(ascending=False)
most_revenue_customer_type = revenue_by_customer_type.index[0]
highest_revenue_amount = revenue_by_customer_type.iloc[0]

print(revenue_by_customer_type)
print(f"\nThe customer type that generates the most revenue is: {most_revenue_customer_type} with a total of ${highest_revenue_amount:,.2f}")

# 3. How does order priority affect revenue?
revenue_by_priority = retail.groupby('Order Priority')['Total'].sum().sort_values(ascending=False)
print("Revenue by Order Priority:")
print(revenue_by_priority)

sns.barplot(x=revenue_by_priority.index, y=revenue_by_priority.values, palette='viridis')
plt.title('Total Revenue by Order Priority')
plt.xlabel('Order Priority')
plt.ylabel('Total Revenue')
plt.tight_layout()
plt.show()

# 4. What is the average profit margin by product category?
retail['Profit Margin'] = retail['Profit Margin'].replace(r'[$,]', '', regex=True).astype(float)
aprofit_by_category = retail.groupby('Product Category')['Profit Margin'].mean().sort_values(ascending=False)
print("Average profit By Product Category:")
print(aprofit_by_category)

# 5. What is the most profitable product overall?
retail['Profit Margin'] = retail['Profit Margin'].replace(r'[$,]','', regex=True).astype(float)
most_profit_product = retail.groupby('Product Name')['Profit Margin'].sum().sort_values(ascending=False)
no_1_Profitable_Product = most_profit_product.index[0]
amount = most_profit_product.iloc[0]

print(most_profit_product)
print(f"\nThe customer type that generates the most revenue is: {no_1_Profitable_Product} with a total of ${amount:,.2f}")

# 6. How many days does it usually take to ship an order?
retail['Shipping Duration'] = (retail['Ship Date'] - retail['Order Date']).dt.days
print(f"The Average days Usually Takes To Ship An Order Is: {retail['Shipping Duration'].mean()} Days")

# 7. Do longer shipping times impact profit margins?
retail['Profit Margin'] = retail['Profit Margin'].astype(str).str.replace(r'[$,]', '', regex=True).astype(float)
correlation = retail['Shipping Duration'].corr(retail['Profit Margin'])
print(f"Correlation between Shipping Duration and Profit Margin: {correlation:.4f}")

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Shipping Duration', y='Profit Margin', data=retail)
plt.title('Shipping Duration vs. Profit Margin')
plt.xlabel('Shipping Duration (Days)')
plt.ylabel('Profit Margin')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# 8. Which city brings in the highest revenue?
retail['Revenue Total'] = retail['Total'].replace(r'[$,]','', regex=True).astype(float)
revenue_per_city = retail.groupby('City')['Revenue Total'].sum().sort_values(ascending=False)
print(f"The City Which Brings The Highest Revenue Is {revenue_per_city.index[0]} With Total Revenue Of {revenue_per_city.iloc[0]}")

# 9. Which account manager generated the most revenue?
revenue_by_AC = retail.groupby('Account Manager')['Revenue Total'].sum().sort_values(ascending=False)
print(f"The Account Manager Which Generates The Most Revenue Is {revenue_by_AC.index[0]} With Total Revenue Of {revenue_by_AC.iloc[0]}")

# 10. Which shipping mode is most cost-effective (lowest avg. shipping)?
retail['Shipping Cost'] = retail['Shipping Cost'].astype(str).str.replace(r'[^\d.]', '', regex=True).astype(float)
average_shipping_cost_by_mode = retail.groupby('Ship Mode')['Shipping Cost'].mean()
most_cost_effective_mode = average_shipping_cost_by_mode.idxmin()
lowest_avg_cost = average_shipping_cost_by_mode.min()
print(f"The most cost-effective shipping mode (lowest average shipping cost) is: {most_cost_effective_mode} with an average cost of ${lowest_avg_cost:.2f}")

# 11. Do higher discounts reduce profits?
correlation = retail['Discount %'].corr(retail['Profit Margin'])
print(f"Correlation between Discount % and Profit Margin: {correlation:.4f}")

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Discount %', y='Profit Margin', data=retail)
plt.title('Discount % vs. Profit Margin')
plt.xlabel('Discount %')
plt.ylabel('Profit Margin')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

# 12. Which state has the highest number of orders?
orders_by_state = retail['State'].value_counts()
highest_order_state = orders_by_state.index[0]
num_orders = orders_by_state.iloc[0]
print(f"The state with the highest number of orders is: {highest_order_state} with {num_orders} orders.")

# 13. What is the average discount % across all orders?
average_discount_percentage = retail['Discount %'].mean()
print(f"The average discount percentage across all orders is: {average_discount_percentage:.2f}%")

# 14. What is the average total spend per order?
retail['Total'] = retail['Total'].astype(str).str.replace(r'[$,]', '', regex=True).astype(float)
average_total_spend = retail['Total'].mean()
print(f"The average total spend per order is: ${average_total_spend:,.2f}")

# 15. Are certain containers (e.g., Small Box, Wrap Bag) more profitable?

profit_by_container = retail.groupby('Product Container')['Profit Margin'].sum().sort_values(ascending=False)
print("Profit Margin by Product Container:")
print(profit_by_container)

sns.barplot(x=profit_by_container.index, y=profit_by_container.values, palette='viridis')
plt.title('Total Profit Margin by Product Container')
plt.xlabel('Product Container')
plt.ylabel('Total Profit Margin')
plt.tight_layout()
plt.show()